### ISSUE TITLE
어떤 영상들을 볼까요?

### ISSUE THREAD

**Issue by samuel950523** [samuel950523/Techo-Talk-Study#2]
[우아한 Tech Youtube](https://www.youtube.com/c/%EC%9A%B0%EC%95%84%ED%95%9CTech/videos)
[해당 링크](https://www.youtube.com/watch?v=FiK0Hu5Pr3Q&list=PLgXGHBqgT2TvpJ_p9L_yZKPifgdBOzdVH) 아래서부터 올라오면서 들을만한 것들을 추려본 것입니다. 빼도 좋겠다 또는 넣었으면 좋겠다는 영상 댓글로 부탁드립니다!
괄호 안의 숫자는 해당 주제에 관한 영상의 숫자입니다.

- Cache (2)
- JPA와 JDBC, ORM (3)
- RESTful
- 웹서버 vs WAS (3)
- 빌드용어
- TCP / UDP
- API vs Library vs Framework (3)
- Process & Thread (3)
- Context Switching
- Connection Pool & Keep-Alive
- Forward Proxy vs Reverse Proxy, Load Balancer (3)
- TLS
- JVM Garbage Collector (2)
- Apache MPM vs NGINX vs Node.js
- JVM Stack & Heap
- CORS (3)
- scale up vs scale out, SPOF
- DB Optimizer
- Clustered vs Non-clustered Index
- Sharding, Clustering, Replication
- 트랜잭션 메커니즘 (2)
- JDK Dynamic Proxy vs CGLIB Proxy
- Generics (2)
- 빌드와 배포 (2)
- Block vs Non-Block & Sync vs Async (2)
- OSI 7 Layer
- HTTP/1.1, HTTP/2, QUIC
- Webflux (댓글이 별로 ㅠㅠ)
- Spring IoC/DI
- AOP
- Spring Security
- Realtime Web
- 도메인 주도 설계 (영상을 안 보긴 했지만 짧은 시간동안 잘 다뤘을지 의문이네요)
- DNS
- 교착상태
- Web Socket
- 데이터베이스 락
- Redis
- Spring Batch

**Comment by kwj1270** [comment]
`도메인 주도 설계`는 처음 보시는 분들에게 좀 난해 할 수 있을 것 같아요

**Comment by samuel950523** [comment]
저도 본문에 썼지만 DDD는 짧은 영상으로 녹이기 어려울 것 같네요. 빼보도록하겠습니다!
